# Generated by Django 4.0.5 on 2023-04-06 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='name')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='code')),
                ('domain', models.CharField(max_length=50, unique=True, verbose_name='domain')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('cors', models.JSONField(default=list, verbose_name='allowed urls')),
            ],
            options={
                'db_table': 'organizations',
            },
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.UniqueConstraint(fields=('code',), name='unique appversion'),
        ),
    ]
