# Generated by Django 4.0.5 on 2023-04-06 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        ('deals', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal', to='users.customer'),
        ),
        migrations.AddField(
            model_name='deal',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organization.organization', verbose_name='data of organization'),
        ),
        migrations.AddField(
            model_name='deal',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal', to='deals.dealtype'),
        ),
        migrations.AddConstraint(
            model_name='dealtype',
            constraint=models.UniqueConstraint(fields=('name', 'org'), name='unique by org and type name'),
        ),
    ]
