# Generated by Django 4.0.5 on 2023-04-06 15:41

from django.db import migrations, models
import django.db.models.deletion
import uuid
import videofiles.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('films', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('season', models.PositiveSmallIntegerField(default=1, verbose_name='season of film')),
                ('series', models.PositiveIntegerField(default=1, verbose_name='film series')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='video', to='films.film', verbose_name='film info')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organization.organization', verbose_name='data of organization')),
            ],
            options={
                'db_table': 'video',
            },
        ),
        migrations.CreateModel(
            name='VideoFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resolution', models.CharField(choices=[(480, '480'), (720, '720'), (1080, '1080'), (2160, '2160')], default=480, max_length=4, verbose_name='video resolution')),
                ('file', models.FileField(max_length=512, null=True, upload_to=videofiles.models.videofile_path)),
                ('sound_studio', models.CharField(max_length=64)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organization.organization', verbose_name='data of organization')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videofiles', to='videofiles.video', verbose_name='video of file')),
            ],
            options={
                'db_table': 'videofiles',
            },
        ),
        migrations.CreateModel(
            name='SubtitleFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(null=True, upload_to='subtitle')),
                ('studio_name', models.CharField(max_length=64)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organization.organization', verbose_name='data of organization')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtitlefiles', to='videofiles.video', verbose_name='subtitle of file')),
            ],
            options={
                'db_table': 'subtitlefiles',
            },
        ),
        migrations.AddConstraint(
            model_name='videofile',
            constraint=models.UniqueConstraint(fields=('video', 'resolution', 'sound_studio'), name='unique resolution of file for video'),
        ),
        migrations.AddConstraint(
            model_name='video',
            constraint=models.UniqueConstraint(fields=('film', 'season', 'series'), name='unique series by season'),
        ),
        migrations.AddConstraint(
            model_name='subtitlefile',
            constraint=models.UniqueConstraint(fields=('video', 'studio_name'), name='unique subtitle file for studio'),
        ),
    ]
